// <auto-generated />
using DungeonsAndYou.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DungeonsAndYou.Data.Migrations
{
    [DbContext(typeof(DungeonsAndYouContext))]
    [Migration("20231105031525_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DungeonsAndYou.Data.Models.CharacterSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Acrobatics")
                        .HasColumnType("int");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AnimalHandling")
                        .HasColumnType("int");

                    b.Property<int>("Arcana")
                        .HasColumnType("int");

                    b.Property<int>("Athletics")
                        .HasColumnType("int");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BackgroundProficientSkills")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("CharismaModifier")
                        .HasColumnType("int");

                    b.Property<int>("CharismaSave")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClassPrimaryAbilities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClassProficientSkills")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClassSavingProficiencies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("ConstitutionModifier")
                        .HasColumnType("int");

                    b.Property<int>("ConstitutionSave")
                        .HasColumnType("int");

                    b.Property<int>("Deception")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("DexterityModifier")
                        .HasColumnType("int");

                    b.Property<int>("DexteritySave")
                        .HasColumnType("int");

                    b.Property<int>("History")
                        .HasColumnType("int");

                    b.Property<int>("HitDie")
                        .HasColumnType("int");

                    b.Property<int>("Initiative")
                        .HasColumnType("int");

                    b.Property<int>("Insight")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceModifier")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceSave")
                        .HasColumnType("int");

                    b.Property<int>("Intimidation")
                        .HasColumnType("int");

                    b.Property<int>("Investigation")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("MaxHitPoints")
                        .HasColumnType("int");

                    b.Property<int>("Medicine")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Nature")
                        .HasColumnType("int");

                    b.Property<int>("PassiveWisdom")
                        .HasColumnType("int");

                    b.Property<int>("Perception")
                        .HasColumnType("int");

                    b.Property<int>("Performance")
                        .HasColumnType("int");

                    b.Property<int>("Persuasion")
                        .HasColumnType("int");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("int");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RaceAbilityBonusses")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Religion")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("SleightOfHand")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Stealth")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("StrengthModifier")
                        .HasColumnType("int");

                    b.Property<int>("StrengthSave")
                        .HasColumnType("int");

                    b.Property<int>("Survival")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.Property<int>("WisdomModifier")
                        .HasColumnType("int");

                    b.Property<int>("WisdomSave")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharacterSheets");

                    b.HasData(
                        new
                        {
                            Id = 1325962638,
                            Acrobatics = 2,
                            Alignment = "neutralGood",
                            AnimalHandling = 3,
                            Arcana = 6,
                            Athletics = 2,
                            Background = "Sage",
                            BackgroundProficientSkills = "4,5",
                            Charisma = 17,
                            CharismaModifier = 3,
                            CharismaSave = 5,
                            Class = "Bard",
                            ClassPrimaryAbilities = "5",
                            ClassProficientSkills = "14,17,16",
                            ClassSavingProficiencies = "1,5",
                            Constitution = 11,
                            ConstitutionModifier = 0,
                            ConstitutionSave = 0,
                            Deception = 5,
                            Dexterity = 15,
                            DexterityModifier = 2,
                            DexteritySave = 4,
                            History = 6,
                            HitDie = 8,
                            Initiative = 2,
                            Insight = 3,
                            Intelligence = 18,
                            IntelligenceModifier = 4,
                            IntelligenceSave = 4,
                            Intimidation = 3,
                            Investigation = 4,
                            Level = 1,
                            MaxHitPoints = 8,
                            Medicine = 3,
                            Name = "Marvin",
                            Nature = 4,
                            PassiveWisdom = 13,
                            Perception = 3,
                            Performance = 5,
                            Persuasion = 5,
                            ProficiencyBonus = 2,
                            Race = "Human",
                            RaceAbilityBonusses = "0,1,2,3,4,5",
                            Religion = 4,
                            Size = "m",
                            SleightOfHand = 2,
                            Speed = 30,
                            Stealth = 2,
                            Strength = 15,
                            StrengthModifier = 2,
                            StrengthSave = 2,
                            Survival = 3,
                            Wisdom = 16,
                            WisdomModifier = 3,
                            WisdomSave = 3
                        },
                        new
                        {
                            Id = -636489837,
                            Acrobatics = 2,
                            Alignment = "neutralGood",
                            AnimalHandling = 3,
                            Arcana = 6,
                            Athletics = 2,
                            Background = "Sage",
                            BackgroundProficientSkills = "4,5",
                            Charisma = 17,
                            CharismaModifier = 3,
                            CharismaSave = 5,
                            Class = "Bard",
                            ClassPrimaryAbilities = "5",
                            ClassProficientSkills = "14,17,16",
                            ClassSavingProficiencies = "1,5",
                            Constitution = 11,
                            ConstitutionModifier = 0,
                            ConstitutionSave = 0,
                            Deception = 5,
                            Dexterity = 15,
                            DexterityModifier = 2,
                            DexteritySave = 4,
                            History = 6,
                            HitDie = 8,
                            Initiative = 2,
                            Insight = 3,
                            Intelligence = 18,
                            IntelligenceModifier = 4,
                            IntelligenceSave = 4,
                            Intimidation = 3,
                            Investigation = 4,
                            Level = 1,
                            MaxHitPoints = 8,
                            Medicine = 3,
                            Name = "Marvin",
                            Nature = 4,
                            PassiveWisdom = 13,
                            Perception = 3,
                            Performance = 5,
                            Persuasion = 5,
                            ProficiencyBonus = 2,
                            Race = "Human",
                            RaceAbilityBonusses = "0,1,2,3,4,5",
                            Religion = 4,
                            Size = "m",
                            SleightOfHand = 2,
                            Speed = 30,
                            Stealth = 2,
                            Strength = 15,
                            StrengthModifier = 2,
                            StrengthSave = 2,
                            Survival = 3,
                            Wisdom = 16,
                            WisdomModifier = 3,
                            WisdomSave = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
